// Generated by gencpp from file multilane_sorter/Signal.msg
// DO NOT EDIT!


#ifndef MULTILANE_SORTER_MESSAGE_SIGNAL_H
#define MULTILANE_SORTER_MESSAGE_SIGNAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace multilane_sorter
{
template <class ContainerAllocator>
struct Signal_
{
  typedef Signal_<ContainerAllocator> Type;

  Signal_()
    : header()
    , ac_a(0)
    , ac_b(0)
    , ac_c(0)
    , ac_d(0)  {
    }
  Signal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ac_a(0)
    , ac_b(0)
    , ac_c(0)
    , ac_d(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _ac_a_type;
  _ac_a_type ac_a;

   typedef uint16_t _ac_b_type;
  _ac_b_type ac_b;

   typedef uint16_t _ac_c_type;
  _ac_c_type ac_c;

   typedef uint16_t _ac_d_type;
  _ac_d_type ac_d;





  typedef boost::shared_ptr< ::multilane_sorter::Signal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multilane_sorter::Signal_<ContainerAllocator> const> ConstPtr;

}; // struct Signal_

typedef ::multilane_sorter::Signal_<std::allocator<void> > Signal;

typedef boost::shared_ptr< ::multilane_sorter::Signal > SignalPtr;
typedef boost::shared_ptr< ::multilane_sorter::Signal const> SignalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multilane_sorter::Signal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multilane_sorter::Signal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::multilane_sorter::Signal_<ContainerAllocator1> & lhs, const ::multilane_sorter::Signal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ac_a == rhs.ac_a &&
    lhs.ac_b == rhs.ac_b &&
    lhs.ac_c == rhs.ac_c &&
    lhs.ac_d == rhs.ac_d;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::multilane_sorter::Signal_<ContainerAllocator1> & lhs, const ::multilane_sorter::Signal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace multilane_sorter

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::multilane_sorter::Signal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multilane_sorter::Signal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multilane_sorter::Signal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multilane_sorter::Signal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multilane_sorter::Signal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multilane_sorter::Signal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multilane_sorter::Signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf6d5cfdfe1165ba84740a209c2b5cb1";
  }

  static const char* value(const ::multilane_sorter::Signal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf6d5cfdfe1165baULL;
  static const uint64_t static_value2 = 0x84740a209c2b5cb1ULL;
};

template<class ContainerAllocator>
struct DataType< ::multilane_sorter::Signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multilane_sorter/Signal";
  }

  static const char* value(const ::multilane_sorter::Signal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multilane_sorter::Signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint16 ac_a\n"
"uint16 ac_b\n"
"uint16 ac_c\n"
"uint16 ac_d\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::multilane_sorter::Signal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multilane_sorter::Signal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ac_a);
      stream.next(m.ac_b);
      stream.next(m.ac_c);
      stream.next(m.ac_d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Signal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multilane_sorter::Signal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multilane_sorter::Signal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ac_a: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ac_a);
    s << indent << "ac_b: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ac_b);
    s << indent << "ac_c: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ac_c);
    s << indent << "ac_d: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ac_d);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTILANE_SORTER_MESSAGE_SIGNAL_H
