(cl:in-package multilane_sorter-msg)
(cl:export '(HEADER-VAL
          HEADER
          SENSORSTATUS-VAL
          SENSORSTATUS
          INTERNETSTATUS-VAL
          INTERNETSTATUS
          DATAUPLOADSTATUS-VAL
          DATAUPLOADSTATUS
          SYSTEMWARNING-VAL
          SYSTEMWARNING
          GUIWARNING-VAL
          GUIWARNING
          THROUGHPUTOVERALL-VAL
          THROUGHPUTOVERALL
          THROUGHPUTACCEPTED-VAL
          THROUGHPUTACCEPTED
          THROUGHPUTREJECTED-VAL
          THROUGHPUTREJECTED
          SORTINGUPTIME-VAL
          SORTINGUPTIME
          SYSTEMUPTIME-VAL
          SYSTEMUPTIME
          ACTUATORSTATS-VAL
          ACTUATORSTATS
          LANE_1-VAL
          LANE_1
          LANE_2-VAL
          LANE_2
          LANE_3-VAL
          LANE_3
          LANE_4-VAL
          LANE_4
))